###
### Prepare a contract
# @name prepareContract
POST {{baseUrl}}/api/contracts
Content-Type: application/json

{
  "customerAge": 30,
  "customerHeight": 180,
  "preparedAt": "2023-05-04T12:00:00.000Z",
  "customerId": "d4086a01-0d26-45ec-89d5-2bbdd501309b"
}

###
### Sign a contract
# @name signContract
PATCH {{baseUrl}}/api/contracts/{{contractId}}
Content-Type: application/json

{
  "signedAt": "2023-05-04T14:00:00.000Z"
}

###
### Sign in a future
# @name signContract
PATCH {{baseUrl}}/api/contracts/{{contractId}}
Content-Type: application/json

{
  "signedAt": "2023-05-05T14:00:00.000Z"
}