name: Add Evolutionary Architecture Nuget Source
description: Remove a specific NuGet source and add GitHub NuGet source
inputs:
  github-token:
    description: GitHub token
    required: true
  owner:
    description: Repository owner
    required: true
  path:
    description: "Path to the directory"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up working directory
      run: cd ${{ github.workspace }}/${{ inputs.path }}
      shell: bash
    - name: ls
      run: ls
      shell: bash
    - name: nuget list source
      run: dotnet nuget list source
      shell: bash
    - run: |
        dotnet nuget add source --username ${{ inputs.owner }} --password ${{ inputs.github-token }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ inputs.owner }}/index.json"
        dotnet nuget list source
      shell: bash
