name: Add Evolutionary Architecture Nuget Source
description: Remove a default Evolutionary Architecture nuget source and add with credentials
inputs:
  github-token:
    description: GitHub token
    required: true
  owner:
    description: Repository owner
    required: true
  path:
    description: "Path to the directory"
    required: true
  nuget-source-name:
    description: "Name of the Nuget source"
    required: true
runs:
  using: "composite"
  steps:
    - name: Add Authorized Evolutionary Architecture Nuget Source
      run: |
        cd ${{ github.workspace }}/${{ inputs.path }}
        
        if dotnet nuget list source | grep -q ${{ inputs.nuget-source-name }}; then
          echo "Removing existing nuget source: '${{ inputs.nuget-source-name }}'"
          dotnet nuget remove source '${{ inputs.nuget-source-name }}'
        else
          echo "Nuget source $NugetSourceName does not exist. Skipping removal."
        fi

        dotnet nuget add source --username ${{ inputs.owner }} --password ${{ inputs.github-token }} --store-password-in-clear-text --name ${{ inputs.nuget-source-name }} "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        dotnet nuget list source
      shell: bash
