version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Chapter-1-initial-architecture/Src"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
updates:
  - package-ecosystem: "nuget"
    directory: "/Chapter-2-modules-separation/Src" 
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
updates:
  - package-ecosystem: "nuget"
    directory: "/Chapter-3-microservice-extraction" 
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
updates:
  - package-ecosystem: "nuget"
    directory: "/Chapter-3-microservice-extraction/Fitnet.Common" 
    schedule:
      interval: "daily"
      day: "wednesday"
    open-pull-requests-limit: 5
updates:
  - package-ecosystem: "nuget"
    directory: "/Chapter-3-microservice-extraction/Fitnet.Contracts/Src" 
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
updates:
  - package-ecosystem: "nuget"
    directory: "/Chapter-3-microservice-extraction/Fitnet/Src" 
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
