namespace SuperSimpleArchitecture.Fitnet.Reports.GenerateNewPassesRegistrationsPerMonthReport.Dtos;

public record NewPassesRegistrationsPerMonthDto(int MonthOrder, string MonthName, long RegisteredPasses);