= Chapter 1: Initial Architecture - Focus On Simplicity
:toc:

== Case

=== Overview

When starting a new greenfield application, our focus often shifts to frameworks, libraries, architecture and components that we have heard about from our friends, at conferences, workshops and meetups. As a result, we start to create an overly complicated infrastructure and solution architecture, using components that are not relevant in the beginning.

This is how we fall into the trap associated with the project paradox - we make a lot of decisions at a time when we have almost no prior knowledge about our business domain. As a result, our decisions are usually inaccurate or, if we are lucky, they fit our future needs (a rare case). This means that at some point we will have to change the way we have been thinking, or it will simply be too late and too complex.

In the end, we may have:

- a big ball of mud OR
- big ball of distributed mud

Instead, we should shift our focus and efforts to understanding business processes and preparing the simplest possible solution.

At this point, in the vast majority of cases, you do not need to focus on:

- clean/onion/hexagonal architecture
- microservices
- cache
- tactical Domain-Driven Design
- data streams
- orchestrators

Thanks to this approach:

- we make most decisions only when we need them
- each member of the team has a low entry threshold for the application
- we add components one at a time, so we can build up the knowledge before adding the next components
- we minimise the risk of ending up with spaghetti (however it is still possible!)

This is what _Evolutionary Architecture_ is all about.

[quote]
Always choose architecture based on *your current needs*. *Not a wishful thinking*.

=== Requirements

Fitness Studio ordered a completely new system that we had to implement from scratch. There are 5 main requirements for the MVP that we need to address:

1. A way to create offers for new and existing customers.
2. When the offer is accepted by a customer, it is possible to prepare the contract.
3. The customer can sign the contract.
4. After signing the contract, a new pass is registered for the customer.
5. When the pass expires, a new offer is sent to the customer.

Based on the outcome - success or failure of the application, the requirements will be extended or the system will be dropped (yes, we need to consider both scenarios).

== How to run?

=== Requirements

- .NET SDK
- PostgresSQL
- Docker

=== How to get .NET SDK?

To run the Fitnet application, you will need to have the recent .NET SDK installed on your computer.
Click link:https://dotnet.microsoft.com/en-us/download[here] 
to download it from the official Microsoft website.

=== How to prepare Postgres?

The Fitnet application requires PostgresSQL as a component to work properly. You can either install it directly on your system or launch it using Docker Compose.

To run PostgresSQL using Docker Compose, navigate to the `root` chapter directory using the Terminal and run the command:
1. Build the Docker compose:

[source,shell]
----
 docker-compose up
----

This will start the PostgresSQL service. Once Postgres is up and running, you can proceed to run the Fitnet application.

=== Run the Fitnet Application

There are two options to run the Fitnet application:

==== Option 1: Launch the Fitnet application in an IDE

If you have an IDE installed, you can launch the Fitnet application directly from there by following these steps:

1. Open the project in your IDE.
2. Run the project.
3. The Fitnet application should start running.

[NOTE]
Fitnet supports .NET User Secrets to store local secrets like connection strings on developer machine. 
We encourage you to use this feature to securely store the connection string.
[end]

==== Option 2: Build and run the Fitnet application as a Docker container

If you prefer to run the Fitnet application as a Docker container, you can build and run it using the following steps:

- Build the Docker image:

[source,shell]
----
docker build -t fitnet .
----

- Run the Docker container:
[source,shell]
----
docker run -p 8080:80 --name fitnet-container fitnet
----

The "8080" is the port number on which the container will be exposed, and "myapp" is the name of the image that you built in the previous step. Once the container is up and running, you should be able to access the application by navigating to http://localhost:8080 in your web browser.

That's it! You should now be able to run the application using either one of the above. :thumbsup:

=== How to run Integration Tests?
To run the integration tests for the project located in the Fitnet.IntegrationTests project, you can use either the command:
[source,shell]
----
dotnet test
----
or the `IDE test Explorer`. 

These tests are written using `xUnit` and require `Docker` to be running as they use `test containers` package to run PostgresSQL in a Docker container during testing. 
Therefore, make sure to have `Docker` running before executing the integration tests.