version: '3.9'

services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build: .
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14.3
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
