services:
  fitnet:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Passes=Host=postgres;Database=fitnet;Username=postgres;Password=mysecretpassword
      - ConnectionStrings__Contracts=Host=postgres;Database=fitnet;Username=postgres;Password=mysecretpassword
      - ConnectionStrings__Reports=Host=postgres;Database=fitnet;Username=postgres;Password=mysecretpassword
      - ConnectionStrings__Offers=Host=postgres;Database=fitnet;Username=postgres;Password=mysecretpassword
    build: .
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14.3
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=fitnet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5