// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SuperSimpleArchitecture.Fitnet.Passes.Persistence;

#nullable disable

namespace SuperSimpleArchitecture.Fitnet.Migrations;

[DbContext(typeof(PassesPersistence))]
partial class PassesPersistanceModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("Passes")
            .HasAnnotation("ProductVersion", "7.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("SuperSimpleArchitecture.Fitnet.Passes.Domain.Pass", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<Guid>("CustomerId")
                .HasColumnType("uuid");

            b.Property<DateTimeOffset>("From")
                .HasColumnType("timestamp with time zone");

            b.Property<int>("PassType")
                .HasColumnType("integer");

            b.Property<DateTimeOffset>("To")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.ToTable("Passes", "Passes");
        });
#pragma warning restore 612, 618
    }
}