name: Contracts package workflow

on:
  push:
    branches: [ "main" ]
    paths:
    - 'Chapter-3-microservice-extraction/Fitnet.Contracts/Src/Fitnet.Contracts.IntegrationEvents/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'Chapter-3-microservice-extraction/Fitnet.Contracts/Src/Fitnet.Contracts.IntegrationEvents/**'

env:
  CHAPTER_DIR: 'Chapter-3-microservice-extraction/Fitnet.Contracts/Src'

jobs:
  build:
    defaults:
      run:
        working-directory: ${{ env.CHAPTER_DIR }}
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Add Evolutionary Architecture Nuget Source
      uses: evolutionary-architecture/evolutionary-architecture-by-example/.github@main
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          path: ${{ env.CHAPTER_DIR }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  pack:
    defaults:
      run:
        working-directory: ${{ env.CHAPTER_DIR }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    name: Pack and Publish
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Add Evolutionary Architecture Nuget Source
      uses: evolutionary-architecture/evolutionary-architecture-by-example/.github@main
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          path: ${{ env.CHAPTER_DIR }}
    - name: Pack Project
      run: dotnet pack Fitnet.Contracts.IntegrationEvents/Fitnet.Contracts.IntegrationEvents.csproj -c Release 
    - name: Publish Packages
      run: dotnet nuget push "Fitnet.Contracts.IntegrationEvents/bin/Release/EvolutionaryArchitecture.Fitnet.Contracts.IntegrationEvents.*.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
